#!/usr/bin/env bash
#
# VPNet.io - Virtual Private Network Essential Toolbox
#
# https://github.com/acrossfw/vpnet
#
# inspired by https://hub.docker.com/r/vimagick/shadowsocks-libev/
#
# KcpTun
#

# shellcheck disable=SC1090
source "$ACROSSFW_HOME/vpnet-functions.sh"
vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic

main() {
  kcptunCmd='./bin/server_linux_amd64' # installed by `docker build`

  # 服务端与客户端必须一致的5个参数及含义 - https://lvii.gitbooks.io/outman/content/kcptun.html
  #   --crypt	      加密算法
  #   --datashard	  前向纠错
  #   --key	        密钥
  #   --nocomp	    压缩数据
  #   --parityshard	前向纠错

  # server_linux_amd64 does not accept `--nocomp 1` params, which will cause it parse arguments totally wrong.
  # if we set KCPTUN_NOCOMP=0/"", we just not put any args(as default)
  # if we set KCPTUN_NOCOMP=1/Y, we just set args to '--nocomp'
  NOCOMP=""
  if [[ -n "$KCPTUN_NOCOMP" && "$KCPTUN_NOCOMP" != 0 ]]; then
    NOCOMP="--nocomp"
  fi

  # shellcheck disable=SC2093
  exec $kcptunCmd \
        --crypt       "${KCPTUN_CRYPT:-salsa20}" \
        --datashard   "${KCPTUN_DATASHARD:-10}" \
        --key         "${ADMIN_PASS:-vpnet.io}" \
        --mode        "${KCPTUN_MODE:-fast}" \
        --parityshard "${KCPTUN_PARITYSHARD:-3}" \
        "${NOCOMP}" \
        \
        --dscp        "${KCPTUN_DSCP:-0}" \
        --listen      "0.0.0.0:${PORT_KCPTUN:-554}" \
        --mtu         "${KCPTUN_MTU:-1350}" \
        --rcvwnd      "${KCPTUN_RCVWND:-1024}" \
        --sndwnd      "${KCPTUN_SNDWND:-1024}" \
        --target      "127.0.0.1:${PORT_SHADOWSOCKS:-8388}" \

  echo "ERROR: exec kcptun exited with error code $?"
  sleep 1
  exit 1
}

main "$@"
