#!/bin/bash
#
# VPNet.io - Virtual Private Network Essential Toolbox
#
# https://github.com/acrossfw/vpnet
#
source "$ACROSSFW_HOME/vpnet-functions.sh"
vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic

while [ true ]; do
    npm start
    echo "ERROR: npm start exit with error code $?" >&2
    sleep 1
done