#!/bin/bash
#
# VPNet.io - Virtual Private Network Essential Toolbox
#
# https://github.com/acrossfw/vpnet
#

# shellcheck disable=SC1090
source "$ACROSSFW_HOME/vpnet-functions.sh"
vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic

n=0 # n++ will cause bash exit, because return 0 (???)
while [[ $((++n)) ]]; do
  # npm start
  echo "by pass node temprorary"
  echo "ERROR: npm start exit with error code $?" >&2
  sleep 1000000
done