#!/usr/bin/env bash
#
# VPNet.io - Virtual Private Network Essential Toolbox
# https://github.com/acrossfw/vpnet
#
# pptp
#

# shellcheck disable=SC1090
source "$ACROSSFW_HOME/vpnet-functions.sh"
vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic

main() {
  vpnet::init_config /etc/pptpd.conf
  vpnet::init_config /etc/ppp/pptpd-options

  pptp::init_user

  pptp::exec

  error_code=$?
  echo "exec pptpd exit with error code $error_code"
  sleep 1
  exit $error_code
}

pptp::init_user() {
  # TBD: iterate USERS
  cat << CHAP_SECRETS > /etc/ppp/chap-secrets
    $ADMIN_NAME	*	$ADMIN_PASS	*
CHAP_SECRETS
}

pptp::exec() {
  # operation not permited inside docker
  # modprobe nf_conntrack_pptp nf_nat_pptp
  exec pptpd --fg
}

main "$@"