#!/usr/bin/env bash
#
# VPNet.io - Virtual Private Network Essential Toolbox
#
# https://github.com/acrossfw/vpnet
#
# inspired by https://hub.docker.com/r/vimagick/shadowsocks-libev/
#
# ShadowSocks
#
source "$ACROSSFW_HOME/vpnet-functions.sh"
vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic

main() {
  ss_cmd=ss-server
  exec $ss_cmd -s 0.0.0.0 \
  	-p "${PORT_SHADOWSOCKS:-8388}" \
  	-k "${ADMIN_PASS:-vpnet.io}" \
  	-m "${SHADOWSOCKS_ENCRYPT_METHOD:-aes-256-cfb}" \
  	-t 300 \
  	--fast-open \
  	-d "${DNS:-8.8.8.8}" \
  	-u

  echo "ERROR: exec shadowsocks exited with error code $?"
  sleep 1
  exit -1
}

main "$@"
