#!/bin/sh
#
# VPNet.io - Virtual Private Network Essential Toolbox
# https://github.com/acrossfw/vpnet
#
# ShadowSocks
#
ss_cmd=ss-server
exec $ss_cmd -s 0.0.0.0 \
	-p 8388 \
	-k "${PASSWORD:-$(hostname)}" \
	-m "${SHADOWSOCKS_ENCRYPT_METHOD:-aes-256-cfb}" \
	-t 300 \
	--fast-open \
	-d "${DNS:-8.8.8.8}" \
	-u


err_code=$?
echo "ERROR: exec $ss_cmd exit with code $err_code"
sleep 1
exit $err_code
